"""HW-WFC 코드 생성기.

스케줄링 결과(HWState)를 Triton 커널 설정 코드로 변환한다.
실제 커널 실행은 하지 않으며, 커널 파라미터와 스켈레톤 코드를 문자열로 생성.
"""

from __future__ import annotations

from dataclasses import dataclass

from .state import LayerNode, LayerType, HWState, MemoryLayout


@dataclass
class KernelConfig:
    """단일 레이어의 Triton 커널 설정."""
    layer_name: str
    layer_type: LayerType
    tile_m: int
    tile_n: int
    tile_k: int  # K 차원 타일 (MatMul 전용, 나머지는 0)
    layout: MemoryLayout
    num_warps: int
    num_stages: int

    def to_dict(self) -> dict:
        return {
            "BLOCK_M": self.tile_m,
            "BLOCK_N": self.tile_n,
            "BLOCK_K": self.tile_k,
            "num_warps": self.num_warps,
            "num_stages": self.num_stages,
        }


def _estimate_num_warps(tile_m: int, tile_n: int) -> int:
    """타일 크기에 따른 warp 수 추정.

    타일 면적이 클수록 더 많은 warp가 필요.
    각 warp는 32개 스레드, 보통 타일 면적 / 32로 추정.
    """
    area = tile_m * tile_n
    if area <= 1024:    # 32x32
        return 2
    if area <= 4096:    # 64x64
        return 4
    if area <= 16384:   # 128x128
        return 8
    return 16


def _estimate_num_stages(tile_m: int, tile_n: int) -> int:
    """소프트웨어 파이프라이닝 단계 수 추정.

    타일이 작으면 더 많은 prefetch 단계가 유리.
    """
    area = tile_m * tile_n
    if area <= 1024:
        return 4
    if area <= 4096:
        return 3
    return 2


def _estimate_tile_k(node: LayerNode) -> int:
    """K 차원 타일 크기 추정."""
    if node.layer_type not in (LayerType.LINEAR, LayerType.CONV2D):
        return 0
    k = node.dims.get("K", 0)
    if node.layer_type == LayerType.CONV2D:
        k = node.dims.get("C_in", 1) * node.dims.get("KH", 1) * node.dims.get("KW", 1)
    # BLOCK_K는 보통 32 또는 64, K보다 작거나 같게
    for bk in [64, 32, 16]:
        if k >= bk:
            return bk
    return max(k, 1)


def extract_config(node: LayerNode) -> KernelConfig | None:
    """붕괴된 노드에서 KernelConfig를 추출."""
    if not node.is_collapsed or node.collapsed_state is None:
        return None

    s = node.collapsed_state
    return KernelConfig(
        layer_name=node.name,
        layer_type=node.layer_type,
        tile_m=s.tile_m,
        tile_n=s.tile_n,
        tile_k=_estimate_tile_k(node),
        layout=s.layout,
        num_warps=_estimate_num_warps(s.tile_m, s.tile_n),
        num_stages=_estimate_num_stages(s.tile_m, s.tile_n),
    )


def extract_all_configs(nodes: list[LayerNode]) -> list[KernelConfig]:
    """모든 붕괴된 노드에서 KernelConfig 목록을 추출."""
    configs = []
    for node in nodes:
        cfg = extract_config(node)
        if cfg:
            configs.append(cfg)
    return configs


# ─── Triton 코드 생성 ───────────────────────────────────────


def _stride_comment(layout: MemoryLayout) -> str:
    if layout == MemoryLayout.ROW_MAJOR:
        return "stride_row=N, stride_col=1  # Row-major"
    elif layout == MemoryLayout.COL_MAJOR:
        return "stride_row=1, stride_col=M  # Column-major"
    else:
        return "# Block-tiled: custom stride per block"


def generate_matmul_kernel(cfg: KernelConfig) -> str:
    """Linear/MatMul 레이어의 Triton 커널 스켈레톤."""
    return f'''\
@triton.jit
def {cfg.layer_name}_kernel(
    A_ptr, B_ptr, C_ptr,
    M, N, K,
    stride_am, stride_ak,
    stride_bk, stride_bn,
    stride_cm, stride_cn,
    BLOCK_M: tl.constexpr = {cfg.tile_m},
    BLOCK_N: tl.constexpr = {cfg.tile_n},
    BLOCK_K: tl.constexpr = {cfg.tile_k},
):
    """Auto-generated by HW-WFC scheduler.
    Layout: {cfg.layout.name} ({_stride_comment(cfg.layout)})
    Warps: {cfg.num_warps}, Stages: {cfg.num_stages}
    """
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)

    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)

    for k in range(0, K, BLOCK_K):
        offs_k = k + tl.arange(0, BLOCK_K)
        a = tl.load(A_ptr + offs_m[:, None] * stride_am + offs_k[None, :] * stride_ak,
                     mask=(offs_m[:, None] < M) & (offs_k[None, :] < K), other=0.0)
        b = tl.load(B_ptr + offs_k[:, None] * stride_bk + offs_n[None, :] * stride_bn,
                     mask=(offs_k[:, None] < K) & (offs_n[None, :] < N), other=0.0)
        acc += tl.dot(a, b)

    c = acc.to(tl.float16)
    tl.store(C_ptr + offs_m[:, None] * stride_cm + offs_n[None, :] * stride_cn, c,
             mask=(offs_m[:, None] < M) & (offs_n[None, :] < N))
'''


def generate_elementwise_kernel(cfg: KernelConfig) -> str:
    """ReLU/LayerNorm 등 element-wise 레이어의 Triton 커널 스켈레톤."""
    op = "tl.maximum(x, 0.0)" if cfg.layer_type == LayerType.RELU else "x  # placeholder"
    return f'''\
@triton.jit
def {cfg.layer_name}_kernel(
    X_ptr, Y_ptr, N_elements,
    BLOCK_SIZE: tl.constexpr = {cfg.tile_m * cfg.tile_n},
):
    """Auto-generated by HW-WFC scheduler.
    Tile: {cfg.tile_m}x{cfg.tile_n} = {cfg.tile_m * cfg.tile_n} elements
    """
    pid = tl.program_id(0)
    offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offs < N_elements
    x = tl.load(X_ptr + offs, mask=mask)
    y = {op}
    tl.store(Y_ptr + offs, y, mask=mask)
'''


def generate_softmax_kernel(cfg: KernelConfig) -> str:
    """Softmax 레이어의 Triton 커널 스켈레톤."""
    return f'''\
@triton.jit
def {cfg.layer_name}_kernel(
    X_ptr, Y_ptr,
    M, N,
    stride_m, stride_n,
    BLOCK_N: tl.constexpr = {cfg.tile_n},
):
    """Auto-generated by HW-WFC scheduler.
    Row-parallel softmax, tile_n={cfg.tile_n}
    """
    row = tl.program_id(0)
    offs_n = tl.arange(0, BLOCK_N)

    # Pass 1: max
    row_max = -float("inf")
    for start in range(0, N, BLOCK_N):
        cols = start + offs_n
        mask = cols < N
        x = tl.load(X_ptr + row * stride_m + cols * stride_n, mask=mask, other=-float("inf"))
        row_max = tl.maximum(row_max, tl.max(x, axis=0))

    # Pass 2: sum(exp)
    row_sum = 0.0
    for start in range(0, N, BLOCK_N):
        cols = start + offs_n
        mask = cols < N
        x = tl.load(X_ptr + row * stride_m + cols * stride_n, mask=mask, other=-float("inf"))
        row_sum += tl.sum(tl.exp(x - row_max), axis=0)

    # Pass 3: normalize
    for start in range(0, N, BLOCK_N):
        cols = start + offs_n
        mask = cols < N
        x = tl.load(X_ptr + row * stride_m + cols * stride_n, mask=mask, other=-float("inf"))
        y = tl.exp(x - row_max) / row_sum
        tl.store(Y_ptr + row * stride_m + cols * stride_n, y, mask=mask)
'''


def generate_kernel(cfg: KernelConfig) -> str:
    """KernelConfig에 따라 적절한 커널 스켈레톤을 생성."""
    if cfg.layer_type in (LayerType.LINEAR, LayerType.CONV2D):
        return generate_matmul_kernel(cfg)
    if cfg.layer_type == LayerType.SOFTMAX:
        return generate_softmax_kernel(cfg)
    return generate_elementwise_kernel(cfg)


def generate_launch_config(cfg: KernelConfig, dims: dict[str, int]) -> str:
    """커널 런치 설정 코드 생성."""
    if cfg.layer_type in (LayerType.LINEAR, LayerType.CONV2D):
        m = dims.get("M", dims.get("H", 1) * dims.get("W", 1))
        n = dims.get("N", dims.get("C_out", 1))
        return (
            f"grid = (triton.cdiv({m}, {cfg.tile_m}), "
            f"triton.cdiv({n}, {cfg.tile_n}))\n"
            f"{cfg.layer_name}_kernel[grid]("
            f"A, B, C, {m}, {n}, K, "
            f"**{cfg.to_dict()})"
        )
    if cfg.layer_type == LayerType.SOFTMAX:
        m = dims.get("M", 1)
        return (
            f"grid = ({m},)\n"
            f"{cfg.layer_name}_kernel[grid](X, Y, {m}, N, stride_m, stride_n, "
            f"**{cfg.to_dict()})"
        )
    # element-wise
    total = 1
    for v in dims.values():
        total *= v
    return (
        f"grid = (triton.cdiv({total}, {cfg.tile_m * cfg.tile_n}),)\n"
        f"{cfg.layer_name}_kernel[grid](X, Y, {total}, "
        f"**{cfg.to_dict()})"
    )


def generate_full_pipeline(nodes: list[LayerNode]) -> str:
    """전체 파이프라인의 Triton 코드를 생성."""
    configs = extract_all_configs(nodes)
    if not configs:
        return "# No collapsed nodes to generate code for."

    lines = [
        "import triton",
        "import triton.language as tl",
        "",
        f"# HW-WFC Auto-Generated Triton Kernels ({len(configs)} layers)",
        f"# Generated from schedule result",
        "",
    ]

    for cfg in configs:
        lines.append(generate_kernel(cfg))
        lines.append("")

    lines.append("")
    lines.append("# ─── Launch Configurations ───")
    lines.append("")

    for i, cfg in enumerate(configs):
        node = nodes[i]
        lines.append(f"# {cfg.layer_name} ({cfg.layer_type.name})")
        lines.append(generate_launch_config(cfg, node.dims))
        lines.append("")

    return "\n".join(lines)
